// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type CreateProductRequest struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int64   `json:"stock"`
}

type CreateProductResponse struct {
	Product Product `json:"product"`
}

type DeleteProductRequest struct {
	Id int64 `path:"id"`
}

type DeleteProductResponse struct {
	Message string `json:"message"`
}

type GetProductRequest struct {
	Id int64 `path:"id"`
}

type GetProductResponse struct {
	Product Product `json:"product"`
}

type ListProductsRequest struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type ListProductsResponse struct {
	Products []Product `json:"products"`
	Total    int64     `json:"total"`
}

type Product struct {
	Id          int64   `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int64   `json:"stock"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type UpdateProductRequest struct {
	Id          int64   `path:"id"`
	Name        string  `json:"name,optional"`
	Description string  `json:"description,optional"`
	Price       float64 `json:"price,optional"`
	Stock       int64   `json:"stock,optional"`
}

type UpdateProductResponse struct {
	Product Product `json:"product"`
}

// Order related types
type Order struct {
	Id         int64   `json:"id"`
	UserId     int64   `json:"user_id"`
	ProductId  int64   `json:"product_id"`
	Quantity   int64   `json:"quantity"`
	TotalPrice float64 `json:"total_price"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
}

type CreateOrderRequest struct {
	ProductId int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

type CreateOrderResponse struct {
	Order Order `json:"order"`
}

type GetOrderRequest struct {
	Id int64 `path:"id"`
}

type GetOrderResponse struct {
	Order Order `json:"order"`
}

type ListOrdersRequest struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=10"`
	Status   string `form:"status,optional"`
}

type ListOrdersResponse struct {
	Orders []Order `json:"orders"`
	Total  int64   `json:"total"`
}

// User related types
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Message string `json:"message"`
}

type UpdateOrderStatusRequest struct {
	Id     int64  `path:"id"`
	Status string `json:"status"`
}

type UpdateOrderStatusResponse struct {
	Order Order `json:"order"`
}

type CancelOrderRequest struct {
	Id int64 `path:"id"`
}

type CancelOrderResponse struct {
	Message string `json:"message"`
}
