// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"goapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 注册Swagger文档路由
	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/swagger/*any",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			http.StripPrefix("/swagger/", http.FileServer(http.Dir("swagger"))).ServeHTTP(w, r)
		},
	})
	// 添加重定向到swagger文档页面的路由
	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/swagger",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			http.Redirect(w, r, "/swagger/doc.html", http.StatusMovedPermanently)
		},
	})

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/products",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/products",
				Handler: ListProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/products/:id",
				Handler: UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/products/:id",
				Handler: DeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/products/:id",
				Handler: GetProductHandler(serverCtx),
			},
		},
	)
}
