// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"goapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/products",
				Handler: CreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/products",
				Handler: ListProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/products/:id",
				Handler: UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/products/:id",
				Handler: DeleteProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/products/:id",
				Handler: GetProductHandler(serverCtx),
			},
		},
	)
}
